# Generated by Django 3.2.8 on 2021-11-03 03:09

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('answers', djongo.models.fields.JSONField(default={}, verbose_name=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.console')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modeler',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('clients', models.ManyToManyField(blank=True, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('input', djongo.models.fields.JSONField(default={}, verbose_name=True)),
                ('output', djongo.models.fields.JSONField(default={}, verbose_name=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.endpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domain')),
                ('modeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modeler')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('modeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_creator', to='api.modeler')),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('ID', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('modeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementation_creator', to='api.modeler')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_question', to='api.question')),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.integration'),
        ),
        migrations.AddField(
            model_name='console',
            name='modeler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modeler'),
        ),
    ]
